baseURL = 'https://fl-tech.ch/'
languageCode = 'de-ch'
title = 'fl-tech&design'
theme = 'PaperMod'

[languages]
  [languages.de]
    languageName = 'Deutsch'
    weight = 1
    title = 'fl-tech&design'
    [languages.de.params]
      description = 'Portfolio & Tech Projects by Hanspeter Flütsch'

  [languages.en]
    languageName = 'English'
    weight = 2
    title = 'fl-tech&design'
    [languages.en.params]
      description = 'Portfolio & Tech Projects by Hanspeter Flütsch'

[params]
  defaultTheme = 'dark'
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  
  [params.profileMode]
    enabled = true
    title = 'fl-tech&design'
    subtitle = 'Portfolio & Tech Projects by Hanspeter Flütsch'
    
    [[params.profileMode.buttons]]
      name = 'Projekte'
      url = 'projects'
      
    [[params.profileMode.buttons]]
      name = 'Über mich'
      url = 'about'

[[menu.main]]
  identifier = "home"
  name = "Start"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "projects"
  name = "Projekte"
  url = "/projects/"
  weight = 2

[[menu.main]]
  identifier = "ideas"
  name = "Ideen"
  url = "/ideas/"
  weight = 3

[[menu.main]]
  identifier = "musik"
  name = "Musik"
  url = "/musik/"
  weight = 4

[[menu.main]]
  identifier = "contact"
  name = "Kontakt"
  url = "/contact/"
  weight = 5

[[menu.main]]
  identifier = "about"
  name = "Über mich"
  url = "/about/"
  weight = 6